### ISSUE TITLE
Syntax error in css files

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/summitregistations-2018#8]
**ERROR in ./~/css-loader!./client/app/registration/registration.css
Module build failed: Error: Unexpected "(" found.**
  at new error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:29:23)
  at Parser.error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:234:15)
  at Parser.pseudo (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:362:18)
  at Parser.parse (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:551:22)
  at Parser.loop (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:519:18)
  at new Parser (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:104:21)
  at Processor.process (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:26:21)
  at getParsed (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:32:59)
  at optimise (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:139:21)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:241:28
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:148:26
  at Root.each (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:114:22)
  at Root.walk (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:147:21)
  at Root.walkRules (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:239:25)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:165:20
  at LazyResult.run (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:274:20)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:189:32)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:194:27

 @ ./~/css-loader!./~/postcss-loader!./client/app/app.css 9:10-93

**ERROR in ./client/app/app.css
Module build failed: ModuleBuildError: Module build failed: Error: Unexpected "(" found.**
  at new error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:29:23)
  at Parser.error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:234:15)
  at Parser.pseudo (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:362:18)
  at Parser.parse (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:551:22)
  at Parser.loop (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:519:18)
  at new Parser (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:104:21)
  at Processor.process (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:26:21)
  at getParsed (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:32:59)
  at optimise (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:139:21)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:241:28
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:148:26
  at Root.each (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:114:22)
  at Root.walk (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:147:21)
  at Root.walkRules (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:239:25)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:165:20
  at LazyResult.run (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:274:20)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:189:32)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
  at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:194:27

  at DependenciesBlock.onModuleBuildFailed (/home/user2/public_html/summitregistations-2018/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
  at nextLoader (/home/user2/public_html/summitregistations-2018/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
  at /home/user2/public_html/summitregistations-2018/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
  at context.callback (/home/user2/public_html/summitregistations-2018/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
  at Object.<anonymous> (/home/user2/public_html/summitregistations-2018/node_modules/css-loader/lib/loader.js:32:18)
  at /home/user2/public_html/summitregistations-2018/node_modules/css-loader/lib/processCss.js:223:4

Child html-webpack-plugin for "../client/index.html":
    
Child extract-text-webpack-plugin:
    
    **ERROR in ./~/css-loader!./client/app/registration/registration.css
    Module build failed: Error: Unexpected "(" found.**
      at new error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:29:23)
      at Parser.error (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:234:15)
      at Parser.pseudo (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:362:18)
      at Parser.parse (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:551:22)
      at Parser.loop (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:519:18)
      at new Parser (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/parser.js:104:21)
      at Processor.process (/home/user2/public_html/summitregistations-2018/node_modules/postcss-selector-parser/dist/processor.js:26:21)
      at getParsed (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:32:59)
      at optimise (/home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:139:21)
      at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:241:28
      at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:148:26
      at Root.each (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:114:22)
      at Root.walk (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:147:21)
      at Root.walkRules (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/container.js:239:25)
      at /home/user2/public_html/summitregistations-2018/node_modules/postcss-minify-selectors/dist/index.js:165:20
      at LazyResult.run (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:274:20)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:189:32)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at LazyResult.asyncTick (/home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:201:22)
      at /home/user2/public_html/summitregistations-2018/node_modules/postcss/lib/lazy-result.js:194:27
    
     @ ./~/css-loader!./~/postcss-loader!./client/app/app.css 9:10-93

@avinashselvam @Ronitron007 check if there are any syntactical errors in the css files. If so, change it and push it to a **separate branch**. If you couldnt find any, reply not found and close the issue.

**Comment by gokulan97** [comment]
Or alternatively, do `gulp build` and we need to fix the error that comes up.

**Comment by gokulan97** [comment]
Done!
